[package]
name = "neko"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23.0"
deno_bindgen = "0.7.0"

[lib]
crate-type = ["cdylib"]